### ISSUE TITLE
Error with 3.0

### ISSUE THREAD

**Issue by Gerber-Media** [bludit-themes/editorial#1]
Trows the following Error on 3.0:
Fatal error: Uncaught Error: Call to undefined method Theme::fontAwesome() in /var/www/vhosts/Domainname/httpdocs/bl-themes/editorial-master/php/head.php:10 Stack trace: #0 /var/www/vhosts/Domainname/httpdocs/bl-themes/editorial-master/index.php(8): include() #1 /var/www/vhosts/Domainname/httpdocs/bl-kernel/boot/site.php(32): include('/var/www/vhosts...') #2 /var/www/vhosts/Domainname/httpdocs/index.php(41): require('/var/www/vhosts...') #3 {main} thrown in /var/www/vhosts/Domainname/httpdocs/bl-themes/editorial-master/php/head.php on line 10

**Comment by dignajar** [comment]
Hi, yes the Themes and Plugins are not yet full support for the version 3.0

**Comment by dignajar** [comment]
Fixed for Bludit v3.x

**Comment by Gerber-Media** [comment]
thumbs up
